[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[functions]
external_node_modules = ["express", "@supabase/supabase-js", "serverless-http"]

# Proxy /api/* to the Express function
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

# React Router / Vite SPA fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
